config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }

  root to: "home#index"

  get "webmaster" => "webmasters#webmaster"
  get "my_profile" => "users#my_profile"

  resources :users, only: [:show] do 
  	put :make_webmaster, to: "webmasters#make_webmaster", on: :member
  	put :renounce_webmaster, to: "webmasters#renounce_webmaster", on: :member
  	delete :delete_user, to: "webmasters#delete_user", on: :member
  end

  resources :articles, controller: "articles/articles" do
    get :editions, on: :member
    get "show_edition/:id_edition", on: :member, action: :show_edition
    put "restore/:id_edition", on: :member, action: :restore
  end
end

app/models/articles/article.rb
module Articles
	class Article < ApplicationRecord

		has_many :article_editions
		has_many :users, through: :article_editions

		validates :article_editions, length: { minimum: 1 }

		attr_accessor :picture
		attr_accessor :content

		def article_owner
			article_editions.first.user
		end

		def is_article_owner? user
			article_owner == user
		end

		def last_edition
			article_editions.last
		end

		def picture
			last_edition.picture
		end

		def content
			last_edition.content
		end

		def last_modification_date
			last_edition.created_at
		end
	end
end

app/models/articles/article_edition.rb
module Articles
	class ArticleEdition < ApplicationRecord

		belongs_to :user
		belongs_to :article

		validates :user, presence: true
		validates :article, presence: true

		mount_uploader :picture, ArticlePictureUploader
  	validates :picture, file_size: { less_than_or_equal_to: ::PictureUploader::MAX_SIZE, greater_than_or_equal_to: ::PictureUploader::MIN_SIZE }


  	def first_edition?
  		article.try(:article_editions).try(:first) == self
  	end

  	def characters_added
  		content.try(:size) || 0
  	end
	end
end

app/controllers/articles/articles_controller.rb
module Articles
	class ArticlesController < BaseController
		before_action :set_resource, only: [:show, :edit, :update, :destroy, :editions, :show_edition, :restore]
		before_action :check_article_owner_rights!, only: [:show, :edit, :update, :destroy]
		before_action :decorate_resource, only: [:new, :show, :edit, :editions, :show_edition]

		def new
			@resource.article_editions << ArticleEdition.new(article: @resource, user: current_user)
			render "articles/new"
		end

		def create
			@resource.title = article_params[:title]
			@resource.key_words = article_params[:key_words]
			@resource.article_editions << ArticleEdition.new(article: @resource, user: current_user, content: article_params[:content], picture: article_params[:picture])

			if @resource.save
				flash[:notice] = "Artículo creado correctamente."
				redirect_to article_path(@resource)
			else
				set_errors_based_on_resource
				render "articles/new"
			end
		end

		def show
			render "articles/show"
		end

		def edit
			render "articles/edit"
		end

		def update
			if article_params[:title] || article_params[:key_words]
				if @has_current_user_article_owner_right
					unless @resource.update(title: article_params[:title], key_words: article_params[:key_words])
						set_errors_based_on_resource
						redirect_to edit_article_path(@resource)
					end
				else
					flash[:alert] = "Debes ser el creador del artículo o tener privilegios de webmaster para poder modificar el título o las palabras clave."
					redirect_to article_path(@resource)
				end
			end

			if article_params[:picture] || article_params[:content]
				unless @resource.article_editions << Articles::ArticleEdition.new(article: @resource, user: current_user, content: article_params[:content], picture: article_params[:picture])
					set_errors_based_on_resource
					redirect_to edit_article_path(@resource)
				end
			end

			flash[:notice] = "Artículo modificado correctamente."
			redirect_to article_path(@resource)
		end

		def destroy
			if @has_current_user_article_owner_right
				if @resource.destroy
					flash[:notice] = "Artículo eliminado correctamente."
					redirect_to root_path
				else
					set_errors_based_on_resource
					redirect_to article_path(@resource)
				end
			else
				flash[:alert] = "Debes ser el creador del artículo o tener privilegios de webmaster para poder eliminar este artículo."
				redirect_to root_path
			end
		end

		def editions
			render "articles/editions"
		end

		def show_edition
			render "articles/show_edition"
		end

		def restore

		end


		private

		def article_params
			params.require(:articles_article).permit(:title, :key_words, :content, :picture)
		end

		def check_article_owner_rights!
			user = current_user
			@has_current_user_article_owner_right = user.webmaster? || @resource.is_article_owner?(user)
		end

		def resource_type
			Article
		end

		def decorate_resource?
			true
		end

		def resource_not_found_msg
			"El artículo que intentas buscar no existe, intentelo de nuevo."
		end
	end
end

app/views/articles/edit.html.haml
.main-wall
	= simple_form_for(@resource, url: article_path(@resource), html: {method: :put, class: "edit-profile-form", :multipart => true }) do |f|
		.row
			.section.col-md-12
				%center
					%h2= "Edición del artículo '#{@resource.title}':"

				.section-box
					- unless current_user.has_edited_any_article?
						.row
							.col-md--12
								.text-box
									.title-text-box
										¿Es la primera vez que editas un artículo?
									.content-text-box
										%p
											Si esta es tu primera edición de un artículo, te recomendamos leer antes estos consejos:
										%ul
											%li= "El titulo y las palabras clave, son tarea del creador del artículo y de los webmasters, por lo que si no eres webmaster ni has creado el artículo no podrás modificarlos."
											%li= "El contenido que añadas o elimines debe mejorar siempre la veracidad del artículo y ampliar la información que este ofrezca, el creador de este o los webmasters podrán restaurar el artículo a un estado anterior si consideran que tu modificación no es apropiada."
											%li= "Si elijes una nueva imagen, esta debe representar el nuevo contenido del artículo."

					%br
					%br
					.row
						.col-md-6.col-sm-12
							.subsection-boxarticle-picture
								.title-section-box= "Imagen del artículo"
								.content-section-box
									= f.input :picture, as: :picture, label: false, id: "upload_profile-picture", version: :normal, class: "article-picture"

						.col-md-6.col-sm-12
							.subsection-box
								.title-section-box= "Información de básica"
								%br
								.content-section-box
									- if @has_current_user_article_owner_right
										= f.input_field :title, autofocus: true, autocomplete: "title", placeholder: "Título", class: "input-string"
										= f.input_field :key_words, autofocus: true, autocomplete: "key_words", placeholder: "Palabras clave.", class: "input-string", aria: { describedby: "help_text_user_name" }
										%small.form-text.text-muted.text-help{ id: "help_text_user_name" }
											Las palabras clave serán usadas para indexar el artículo.
									- else
										%p
											Solo él creadores del artículo o los usuarios con privilegios de webmaster pueden editar la información básicat.
									%br
									%br
									.profile-attribute
										.attribute-content
											= link_to "Página del artículo", article_path(@resource), method: :get, class: "btn btn-outline-primary"
											= link_to "Ediciones", editions_article_path(@resource), method: :get, class: "btn btn-outline-primary"
											- if @has_current_user_article_owner_right
												= link_to "Eliminar artículo", article_path, method: :delete, class: "btn btn-outline-danger"
					.row
						.col-md-12
							.subsection-box
								.title-section-box= "Contenido del artículo"
								.content-section-box
									= hidden_field_tag 'article-content', @resource.content
									= f.text_area :content, :class => "rich-text-editor-for-article"

					.row
						.col-md-12
							= f.button :submit, value: "Modificar artículo", class: "btn btn-lg btn-outline-primary btn-block"

app/views/articles/editions.html.haml
.main-wall
	.row
		.section.col-md-12
			%center
				%h2= "Historial de ediciones de '#{@resource.title}'"

			.section-box
				.row
					.col-md-12
						.subsection-box
							.content-section-box
								%table.table
									%thead
										%tr
											%th= "#"
											- %w(icon created_at user characters_added).each do |edition_attr|
												%th= @resource.send("field_for_edition_#{edition_attr}")
											%th= "Actions"
									%tbody
										- @resource.article_editions.decorate.to_a.reverse.each_with_index do |edition, index|
											%tr
												%td= index+1
												- %w(icon created_at user characters_added).each do |edition_attr|
													%td= edition.send(edition_attr)
												%td
													- if index == 0
														= button_to "Artículo actual", article_path(@resource), method: :get, class: "btn btn-outline-primary btn-sm"
													- else
														= link_to "Ver", editions_article_path(id: @resource.id, id_edition: edition.id), method: :get, class: "btn btn-outline-primary btn-sm"
														= link_to "Restaurar", editions_article_path(id: @resource.id, id_edition: edition.id), method: :put, class: "btn btn-outline-danger btn-sm", data: { confirm: "Estas seguro de que deseas restaurar el artículo? Todas las modificaciones creadas despueés de esta será eliminadas" }

app/views/articles/new.html.haml
.main-wall
	= simple_form_for(@resource, url: articles_path, html: {method: :post, class: "edit-profile-form", :multipart => true }) do |f|
		.row
			.section.col-md-12
				%center
					%h2= "Artículo nuevo:"

				.section-box
					- unless current_user.has_created_any_article?
						.row
							.col-md--12
								.text-box
									.title-text-box
										¿Es este tu primer artículo?
									.content-text-box
										%p
											Si este es tu primer artículo, te damos una serie de consejos para facilitar su creación:
										%ul
											%li= "Elije un título apropiado para tu artículo, de forma que resuma de forma muy breve su contenido."
											%li= "La imagen que elijas debe ser una imagen altamente representativa del contenido del artículo."
											%li= "Las palabres clave serán usadas por el buscador de artículos para ser encontrados, por lo que, si quieres que tu artículo sea facilmente accesible por otros usuarios, te recomendamos usar palabras que tengan gran relación con este."
											%li= "Intenta estructurar bien el contenido del artículo, de esta forma facilitarás su lectura y edición al resto de usaurios de Sepopedia."
										%p
											Puedes consultar algún artículo ya creado a modo de ejemplo, como este.
					%br
					%br
					.row
						.col-md-6.col-sm-12
							.subsection-box
								.title-section-box= "Foto del artículo"
								.content-section-box
									= f.input :picture, as: :picture, label: false, id: "upload_profile-picture", version: :normal, class: "article-picture"

						.col-md-6.col-sm-12
							.subsection-box
								.title-section-box= "Información de básica"
								%br
								.content-section-box
									= f.input_field :title, autofocus: true, autocomplete: "title", placeholder: "Título", class: "input-string"
									= f.input_field :key_words, autofocus: true, autocomplete: "key_words", placeholder: "Palabras clave.", class: "input-string", aria: { describedby: "help_text_user_name" }
									%small.form-text.text-muted.text-help{ id: "help_text_user_name" }
										Las palabras clave serán usadas para indexar el artículo.
					.row
						.col-md-12
							.subsection-box
								.title-section-box= "Contenido del artículo"
								.content-section-box
									= f.text_area :content, :class => "rich-text-editor-for-user-profile"

					.row
						.col-md-12
							= f.button :submit, value: "Crear artículo", class: "btn btn-lg btn-outline-primary btn-block"

app/views/articles/show.html.haml
.main-wall
	.row
		.section.col-md-12
			%center
				%h2= @resource.title

			.section-box
				.row
					.col-md-6.col-sm-12
						.subsection-box
							.content-section-box
								= image_tag(@resource.try(:picture).try(:url, :normal), :class => 'article-picture', id: 'article-picture')

					.col-md-6.col-sm-12
						.subsection-box
							.content-section-box
								- %w(created_at last_modification_date key_words).each do |article_attr|
									- unless @resource.try(article_attr).try(:blank?)
										.profile-attribute
											.attribute-label
												= @resource.try("field_for_#{article_attr}") || article_attr.humanize
											.attribute-content
												= @resource.try(article_attr)
							%br
							.profile-attribute
								.attribute-content
									= link_to "Editar artículo", edit_article_path(@resource), method: :get, class: "btn btn-outline-primary"
									= link_to "Ediciones", editions_article_path(@resource), method: :get, class: "btn btn-outline-primary"
									- if @has_current_user_article_owner_right
										= link_to "Eliminar artículo", article_path, method: :delete, class: "btn btn-outline-danger"

				.row
					.col-md-12
						.subsection-box
							.title-section-box= "Contenido del artículo"
							.content-section-box
								= sanitize @resource.content

app/views/articles/show_edition.haml
.main-wall
	.row
		.section.col-md-12
			%center
				%h2= @resource.article.title
				%he= "(VERSIÓN DEL #{@resource.created_at})"

			.section-box
				.row
					.col-md-6.col-sm-12
						.subsection-box
							.content-section-box
								= image_tag(@resource.try(:picture).try(:url, :normal), :class => 'article-picture', id: 'article-picture')

					.col-md-6.col-sm-12
						.subsection-box
							.content-section-box
								- %w(created_at last_modification_date key_words).each do |article_attr|
									- unless @resource.try(article_attr).try(:blank?)
										.profile-attribute
											.attribute-label
												= @resource.try("field_for_#{article_attr}") || article_attr.humanize
											.attribute-content
												= @resource.try(article_attr)
							%br
							.profile-attribute
								.attribute-content
									= link_to "Editar artículo", edit_article_path(@resource), method: :get, class: "btn btn-outline-primary"
									= link_to "Ediciones", editions_article_path(@resource), method: :get, class: "btn btn-outline-primary"
									- if @has_current_user_article_owner_right
										= link_to "Eliminar artículo", article_path, method: :delete, class: "btn btn-outline-danger"

				.row
					.col-md-12
						.subsection-box
							.title-section-box= "Contenido del artículo"
							.content-section-box
								= sanitize @resource.content