config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'devise/user_registrations' }

  root to: "home#index"

  get "webmaster" => "webmasters#webmaster"
  get "my_profile" => "users#my_profile"

  resources :users, only: [:show] do 
  	put :make_webmaster, to: "webmasters#make_webmaster", on: :member
  	put :renounce_webmaster, to: "webmasters#renounce_webmaster", on: :member
  	delete :delete_user, to: "webmasters#delete_user", on: :member
  end

  resources :articles, controller: "articles/articles" do
    get :editions, on: :member
    get "show_edition/:id_edition", on: :member, action: :show_edition
    put "restore/:id_edition", on: :member, action: :restore
  end
end

app/controllers/webmasters_controller.rb
class WebmastersController < UsersController
	before_action :check_webmaster!
	before_action :set_resource, only: [:show, :delete_user, :make_webmaster]

	def webmaster
		@user = current_user
		@users = User.all.where.not(id: @user.id).decorate 

		render :webmaster
	end

	def delete_user
		unless @resource.webmaster?
			if @resource.destroy
				flash[:notice] = "Usuario eliminado correctamente."
			else
				flash[:alert] = @resource.errors.messages.values.join(", ") + "."
			end

			redirect_to :webmaster
		end
	end

	def make_webmaster
		if !@resource.webmaster?
			if @resource.webmaster!
				flash[:notice] = "Privilegios de webmaster asignados correctamente."
			else
				flash[:alert] = @resource.errors.messages.values.join(", ") + "."
			end
		else
			flash[:alert] = "El usuario ya es webmaster."
		end

		redirect_to :webmaster
	end

	def renounce_webmaster
		@user = current_user.object

		if @user.user!
			flash[:notice] = "Has renunciado correctamente a tus privilegios como webmaster."
		else
			flash[:alert] = @resource.errors.messages.values.join(", ") + "."
		end

		redirect_to :root
	end


	private

	def check_webmaster!
		unless current_user.webmaster?
			flash[:alert] = "Es necesario tener privilegios de webmaster para acceder a esa sección."
			redirect_to :root
		end
	end

	def decorate_resource?
		false
	end
end

app/views/webmasters/webmaster.html.haml
.main-wall
  .row
    .section.col-md-12
      %center
        %h2= "Hola #{@user.name}, este es tu panel de administrador de webmaster."

  .section-box
    .subsection-box
      .title-section-box= "Usuarios de Sepopedia:"
      %br
      .content-section-box
        %table.table
          %thead
            %tr
              %th= "#"
              - %w(email user_name first_name second_name tlf created_at updated_at).each do |user_attr|
                %th= @user.send("field_for_#{user_attr}")
              %th= "Actions"
          %tbody
            - @users.each do |user|
              %tr
                %th= user.id
                %td= user.email_link
                - %w(user_name first_name second_name tlf created_at updated_at).each do |user_attr|
                  %td= user.send(user_attr)
                %td
                  - unless user.webmaster? 
                    = button_to "Webmaster", make_webmaster_user_path(id: user.id), method: :put, class: "btn btn-outline-primary btn-sm", data: { confirm: "Estás seguro de que deseas otorgar privilegios de webmaster al usuario con email '#{user.email}'? Una vez solo hagas ya no podrás quitar dichos privilegios." }
                    = button_to "Eliminar", delete_user_user_path(id: user.id), method: :delete, class: "btn btn-outline-danger btn-sm", data: { confirm: "Estas seguro de que deseas eliminar al usuario con email '#{user.email}'?" }

    .subsection-box
      .title-section-box
        Renunciar a los privilegios de webmaster:
      .content-section-box
        .text-box
          .title-text-box
            ¿Por qué debería renunciar a los privilegios de webmaster?
          .content-text-box
            %p
              Ser webmaster de sepopedia conlleva una responsabilidad que consiste en administrar tanto los usuarios como los artículos de la página, si has sido nombrado webmaster por otro usuario es porque este piensa que serás capaz de acarrerar dicha responsabilidad, si tú crees que no puedes o que no tienes tiempo para ello, es tu deber renunciar a los privilegios de webmaster.
            %p
              Por otra parte, la applicación necesita de almenos un webmaster, por lo que si eres el único webmaster de la página, no se te permitirá ni renunciar a los privilegios ni eliminar tu cuenta. Si esta es tu situación y aun asi quieres renunciar a los privilegios, primero debes nombrar webmaster a otro usuario.

      .title-section-box
        Si deseas renunciar definitivamente a los privilegios de webmaster, haz click en el siguiente botón:
      .content-section-box
        %center
          = button_to "Renunciar a los privilegios de webmaster", renounce_webmaster_user_path(id: @user.id), method: :put, class: "btn btn-outline-danger btn-lg", data: { confirm: "Una vez renuncies a los privilegios de webmaster no podrás volver a recuperarlos a menos que otro usuario te nombre webmaster de nuevo. Estas seguro que deseas continuar?" }
 